### ISSUE TITLE
Infografía Hilos en C#

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/infografia-de-hilos-SANDRAVELASCO#2]
![Infografía de Hilos](https://user-images.githubusercontent.com/71859796/161122252-8bb27e2b-d07c-49e5-89c2-4ffbdc350d3d.gif)
[Infografía de Hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-SANDRAVELASCO/files/8392074/Infografia.de.Hilos.pdf)

**Comment by Yareli-Perez** [comment]
calificación = 20 = 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
